units:
  # padding
  px: u + 4
  py: u + 4
  # half padding
  hx: px / 2
  hy: py / 2
  # case padding
  cs: 3
points:
  zones:
    matrix:
      anchor:
        shift: [100, -200]
      columns:
        macro:
          key.column_net: P104
        outer:
          key.column_net: P011
        pinky:
          key.stagger: 3
          key.column_net: P100
        ring:
          key.column_net: P024
          key.stagger: 3 + u
        middle:
          key.column_net: P022
          key.stagger: 5
        index:
          key.column_net: P020
          key.stagger: -5
        inner:
          key.column_net: P017
          key.stagger: -6
      rows:
        space:
          row_net: P031
        bottom:
          row_net: P029
        home:
          row_net: P002
        top:
          row_net: P115
        num:
          row_net: P113
  # rotate: -15
  mirror:
    ref: matrix_inner_num
    distance: 2u
outlines:
  keys:
    - where: true
      what: rectangle
      size: [14, 14]
  frame:
    - where: true
      what: rectangle
      size: [px, py]
      fillet: 2
  leftboard:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_macro_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_pinky_num
          shift: [-0.5px, 0.5py-3]
        - ref: matrix_pinky_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_ring_num
          shift: [-0.5px, -0.5py+1]
        - ref: matrix_ring_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_num
          shift: [-hx, hy - 5]
        - ref: matrix_middle_num
          shift: [-hx, hy]
        - ref: matrix_index_num
          shift: [-hx, hy + 5]
        # - ref: matrix_index_num
        #   shift: [-hx, hy]
        # - ref: matrix_inner_num
        #   shift: [-hx , hy+ 6]
        # - ref: matrix_inner_num
        #   shift: [-hx, hy]
        - ref: matrix_inner_num
          shift: [hx, hy]
        - ref: matrix_inner_space
          shift: [hx, -hy-1u]
        # - ref: matrix_pinky_space
        #   shift: [hx, hy-7]
        - ref: matrix_pinky_space
          shift: [hx, -hy-3]
        - ref: matrix_macro_space
          shift: [-hx, -hy]
      fillet: 2
  leftcutout:
    - name: leftboard
    - operation: subtract
      name: keys
  leftcase:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_macro_num
          shift: [-0.5px - cs, 0.5py + cs]
        - ref: matrix_pinky_num
          shift: [-0.5px - cs, 0.5py - 3 + cs]
        - ref: matrix_pinky_num
          shift: [-0.5px - cs, 0.5py + cs]
        - ref: matrix_ring_num
          shift: [-0.5px - cs, -0.5py + 1 + cs]
        - ref: matrix_ring_num
          shift: [-0.5px - cs, 0.5py + cs]
        - ref: matrix_middle_num
          shift: [-hx - cs, hy - 5 + cs]
        - ref: matrix_middle_num
          shift: [-hx - cs, hy + cs]
        - ref: matrix_index_num
          shift: [-hx - cs, hy + 5 + cs]
        # - ref: matrix_index_num
        #   shift: [-hx, hy]
        # - ref: matrix_inner_num
        #   shift: [-hx , hy+ 6]
        # - ref: matrix_inner_num
        #   shift: [-hx, hy]
        - ref: matrix_inner_num
          shift: [hx + cs, hy + cs]
        - ref: matrix_inner_space
          shift: [hx + cs, -hy-1u - cs]
        # - ref: matrix_pinky_space
        #   shift: [hx, hy-7]
        - ref: matrix_pinky_space
          shift: [hx + cs, -hy-3 - cs]
        - ref: matrix_macro_space
          shift: [-hx - cs, -hy - cs]
      fillet: 2
  leftcasecutout:
    - name: leftcase
    - operation: subtract
      name: keys
  rightboard:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_matrix_macro_num
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_pinky_num
          shift: [-0.5px, 0.5py-3]
        - ref: mirror_matrix_pinky_num
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_ring_num
          shift: [-0.5px, -0.5py+1]
        - ref: mirror_matrix_ring_num
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_middle_num
          shift: [-hx, hy - 5]
        - ref: mirror_matrix_middle_num
          shift: [-hx, hy]
        - ref: mirror_matrix_index_num
          shift: [-hx, hy + 5]
        # - ref: matrix_index_num
        #   shift: [-hx, hy]
        # - ref: matrix_inner_num
        #   shift: [-hx , hy+ 6]
        # - ref: matrix_inner_num
        #   shift: [-hx, hy]
        - ref: mirror_matrix_inner_num
          shift: [hx, hy]
        - ref: mirror_matrix_inner_space
          shift: [hx, -hy-1u]
        # - ref: matrix_pinky_space
        #   shift: [hx, hy-7]
        - ref: mirror_matrix_pinky_space
          shift: [hx, -hy-3]
        - ref: mirror_matrix_macro_space
          shift: [-hx, -hy]
      fillet: 2
  rightcutout:
    - name: rightboard
    - operation: subtract
      name: keys
  rightcase:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_matrix_macro_num
          shift: [-0.5px-cs, 0.5py+cs]
        - ref: mirror_matrix_pinky_num
          shift: [-0.5px-cs, 0.5py-3+cs]
        - ref: mirror_matrix_pinky_num
          shift: [-0.5px-cs, 0.5py+cs]
        - ref: mirror_matrix_ring_num
          shift: [-0.5px-cs, -0.5py+1+cs]
        - ref: mirror_matrix_ring_num
          shift: [-0.5px-cs, 0.5py+cs]
        - ref: mirror_matrix_middle_num
          shift: [-hx-cs, hy - 5+cs]
        - ref: mirror_matrix_middle_num
          shift: [-hx-cs, hy+cs]
        - ref: mirror_matrix_index_num
          shift: [-hx-cs, hy + 5+cs]
        # - ref: matrix_index_num
        #   shift: [-hx, hy]
        # - ref: matrix_inner_num
        #   shift: [-hx , hy+ 6]
        # - ref: matrix_inner_num
        #   shift: [-hx, hy]
        - ref: mirror_matrix_inner_num
          shift: [hx+cs, hy+cs]
        - ref: mirror_matrix_inner_space
          shift: [hx+cs, -hy-1u-cs]
        # - ref: matrix_pinky_space
        #   shift: [hx, hy-7]
        - ref: mirror_matrix_pinky_space
          shift: [hx+cs, -hy-3-cs]
        - ref: mirror_matrix_macro_space
          shift: [-hx-cs, -hy-cs]
      fillet: 2
  rightcasecutout:
    - name: rightcase
    - operation: subtract
      name: keys
pcbs:
  left:
    outlines:
      main:
        outline: leftboard
    footprints:
      mx_hotswap:
        where: /^matrix_.*/
        what: mx
        params:
          keycaps: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        where: /^matrix_.*/
        what: diode
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      # microcontroller
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: matrix_inner_space
          shift: [-0.5u, -1u]
          rotate: 180
      # battery jack
      jstph:
        what: jstph
        where:
          ref: matrix_inner_space
          shift: [0, u/2]
          rotate: -90
        params:
          side: B
          pos: pos
          neg: GND
      # Reset switch (horizontal community version)
      horizontal_reset:
        what: EVQPUC
        params:
          side: B
          from: GND
          to: RST
        where:
          ref: matrix_inner_bottom
          shift: [9.0, 0.8-1.2u]
          rotate: -90.0
      # Battery on/off switch
      battery_switch:
        what: slider
        where:
          ref: matrix_inner_bottom
          shift: [8.8, -6]
          rotate: -90
        params:
          side: B
          from: pos
          to: RAW
      # Write "Icarus" on the PCB
      front_text: &text
        what: text
        where: &textWhere
          ref: matrix_middle_space
          shift: [-(u/2)+2.5, -hy-1.5]
        params: &textParams
          text: Icarus
          justify: left
          h_size: 3.0
          v_size: 3.0
          thickness: 0.4
      # holes in PCB
      hole_bottom_left:
        what: mountinghole
        where:
          ref: matrix_macro_space
          shift: [u/2, u/2]
      hole_top_left:
        what: mountinghole
        where:
          ref: matrix_macro_num
          shift: [u/2, -u/2]
      hole_center:
        what: mountinghole
        where:
          ref: matrix_middle_home
          shift: [-u/2, -u/2]
      hole_top_right:
        what: mountinghole
        where:
          ref: matrix_index_num
          shift: [-u/2, -u/2]
      hole_bottom_right:
        what: mountinghole
        where:
          ref: matrix_index_space
          shift: [u/2, -u/2]
  right:
    outlines:
      main:
        outline: rightboard
    footprints:
      mx_hotswap:
        where: /^mirror_matrix_.*/
        what: mx
        params:
          keycaps: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        where: /^mirror_matrix_.*/
        what: diode
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      # microcontroller
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: mirror_matrix_inner_space
          shift: [-0.5u, -1u]
          # rotate: 180
      # battery jack
      jstph:
        what: jstph
        where:
          ref: mirror_matrix_inner_space
          shift: [0, u/2]
          rotate: -90
        params:
          side: B
          pos: pos
          neg: GND
      # Reset switch (horizontal community version)
      horizontal_reset:
        what: EVQPUC
        params:
          side: B
          from: GND
          to: RST
        where:
          ref: mirror_matrix_inner_bottom
          shift: [9.0, 0.8-1.2u]
          rotate: -90.0
      # Battery on/off switch
      battery_switch:
        what: slider
        where:
          ref: mirror_matrix_inner_bottom
          shift: [8.8, -6]
          rotate: -90
        params:
          side: B
          from: pos
          to: RAW
      # Write "Icarus" on the PCB
      front_text: &text
        what: text
        where: &textWhere
          ref: mirror_matrix_middle_space
          shift: [(u/2)-2.5, -hy-1.5]
        params: &textParams
          text: Icarus
          justify: left
          h_size: 3.0
          v_size: 3.0
          thickness: 0.4
      # holes in PCB
      hole_bottom_left:
        what: mountinghole
        where:
          ref: mirror_matrix_macro_space
          shift: [u/2, u/2]
      hole_top_left:
        what: mountinghole
        where:
          ref: mirror_matrix_macro_num
          shift: [u/2, -u/2]
      hole_center:
        what: mountinghole
        where:
          ref: mirror_matrix_middle_home
          shift: [-u/2, -u/2]
      hole_top_right:
        what: mountinghole
        where:
          ref: mirror_matrix_index_num
          shift: [-u/2, -u/2]
      hole_bottom_right:
        what: mountinghole
        where:
          ref: mirror_matrix_index_space
          shift: [u/2, -u/2]
